"""subsequent  Migration

Revision ID: 29688b8588cd
Revises: f24de40c2e22
Create Date: 2021-09-25 18:00:28.221689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29688b8588cd'
down_revision = 'f24de40c2e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
